### PR TITLE
Update visualize.py

### PR DESCRIPTION
**Pull request by maximecb**

### CODE REVIEW

**Comment by lcswillems** [comment]
Hi Maxime,

I can't get the code running. If I execute the commands given by @abrsvn in this issue https://github.com/lcswillems/rl-starter-files/issues/36 with your code, a new window opens but it gets stuck: nothing appears at the screen and the program seems blocked.

I am on Kubuntu 19.04. What is the modification you did to Gym Minigrid?

**Comment by abrsvn** [comment]
same on my machine (i'm on linux mint 19.3). but it does successfully save
to gif though.

-a

**Comment by maximecb** [comment]
Did you update your `gym_minigrid` package? I pushed a new version to pip on December 16.

**Comment by lcswillems** [comment]
Yes, I am using this version and I have the issue

**Comment by maximecb** [comment]
Can you help me investigate using a gym_minigrid install from the github repo?

Are you on Mac or Linux?

**Comment by lcswillems** [comment]
I have installed from the Github repo (git clone then `pip install -e .`) but still have the issue.

I am on Linux, on Kubuntu 19.10 (same as Ubuntu 19.10), but I am using a special window manager called I3 (so, maybe it is coming from this).

@abrsvn uses Linux mint 19.3 and has the same problem too

**Comment by maximecb** [comment]
I'm on Linux as well, but xubuntu 18.04, with the xfce window manager.

Two questions for you:
- Does the `manual_control.py` script from gym_minigrid work properly for you? If not, what happens when you run it?
- Are you able to run [this matplotlib example](https://matplotlib.org/3.1.0/gallery/images_contours_and_fields/image_demo.html) using `imshow`?

**Comment by maximecb** [comment]
I was able to reproduce the bug on my MacOS laptop (!). It seems to have to do wit the matplotlib backend used on different platforms (blergh). I pushed a fix to the GitHub repo. Can you tell me if the problem is fixed, with a minigrid install from the GitHub repo. If so, I will update the package on pip as well.

**Comment by lcswillems** [comment]
It is nearly working! When I execute the script, the window appear and I can see the baby moving, etc... But when I close the window (with ctrl+w), the window closes but another window opens, and if I close this window, another open again and again.

**Comment by maximecb** [comment]
I added a flag to detect when the window is closed. This new version should behave as you would expect. You will need to do a git pull in minigrid as well. Let me know if it works.

**Comment by maximecb** [comment]
@lcswillems can you test it and merge the PR if it works correctly?

**Pull request merged**
