### PR TITLE
save visualization as gif

### PR DESCRIPTION
**Pull request by mavroudisv**
Just a simple modification that let's you save your visualizations as a gif.

### CODE REVIEW

**Comment by maximecb** [comment]
You should put that import in a try block or import lazily. Otherwise this could break the script if this new dependency fails to install, which is almost certainly going to happen.

**Comment by mavroudisv** [comment]
Hi Maxime, 
thanks for the response. :)

Perhaps something like:

```
if args.gif is not None:
   from array2gif import write_gif
   frames = []
```

would do?

**Comment by maximecb** [comment]
Yes. Just make sure to test that it works.

**Comment by mavroudisv** [comment]
Thanks for the suggestion. I ended up using the code above.

I also thought of just ignoring the gif option if array2gif is not installed, but I think an exception is more informative for the user (i.e., to know why the gif was not generated).

**Comment by lcswillems** [comment]
@mavroudisv Thanks a lot for your PR!!

**Comment by mavroudisv** [comment]
Thank you guys for the awesome project(s). Happy to have helped a bit.

**Pull request merged**
